### ISSUE TITLE
Progress update

### ISSUE THREAD

**Issue by drtudor** [Schumacher-group/ImmuneCellMigrationAnalysis#4]
Progress update:

- Working on the HME code and convergence (See issues)
- Running the Drosophila data with the new time bins 
- Reading up on alternative model comparison methods (Thermodynamic integration, BIC etc.) 

Issue:
- Uploaded the Harmonic mean convergence testing notebook with the synthetic data files, seems to be that HME convergences up to 18,000 and then diverges

**Comment by ljschumacher** [comment]
as this is a trial of using issues for updates we need to see how to best use them. The idea is to enable the update of information before the meeting, so that the meeting itself can be used for problem solving. To this end I suggest:

- providing a date in issue title in format year/month/day
- including links to relevant issues (instead of "see issues", perhaps create an ongoing issue thread for each topic, such as issues with the HME)
- include example results (eg plots)
- include references/sources for reading, and/or short summary of what was learnt?

**Comment by ljschumacher** [comment]
- please also fix axes labels and plot titles in [Harmonic mean convergence testing notebook](https://github.com/ljschumacher/ImmuneCellMigrationAnalysis/blob/82c45052dd6fc606701b372b272823b34b73f939/Notebooks/Harmonic%20mean%20convergence%20testing%20.ipynb), a couple of them are incorrect or confusing

**Comment by drtudor** [comment]
## Agreed points to be reviewed for next meeting:
**Harmonic mean estimator**:
- Change the discard length whilst keeping sample length constant 
- Check convergence of HME by checking number of samples needed 
- Plot the HME for each model separately 
- Run for longer, and/or add more walkers 
- Check that the prior's make sense for the initial concentration model 
- Run concentration model 

**Model comparison**:
- Read up on thermodynamic integration and PyPesto, is it better suited than HME?
- Produce a test notebook with all parameters, and priors clearly labelled
